server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  profiles:
    active: ${ACTIVE_PROFILE}
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: hikari-connection-pool
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: identity-service
    server: http://localhost:${server.port}
    title: Identity Service
    version: 1.0.0
