name: huy-commerce
services:

  kafka:
    image: 'bitnami/kafka:4.0.0'
    container_name: hc_kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  mongodb:
    image: bitnami/mongodb:8.0.6
    container_name: hc_mongodb
    hostname: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: qnguyen
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb:/bitnami/mongodb

  postgres:
    image: postgres:14.17
    container_name: hc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: qnguyen
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5431:5432"

volumes:
  postgres:
  mongodb: