server:
  port: 8081
  servlet:
    context-path: /product

spring:
  application:
    name: product-service
  profiles:
    active: ${ACTIVE_PROFILE}
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: hikari-connection-pool
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    enabled: true
    resolve-schema-properties: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: product-service
    server: http://localhost:${server.port}
    title: Product Service
    version: 1.0.0

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
