spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${POSTGRES_URL}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}