name: Build Feature Branch

on:
    push:
        branches:
        - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package -DskipTests