name: PR Build and Test

on:
    pull_request:
        branches:
        - develop
        - main

jobs:
  detect-changes:
    uses: ./.github/workflows/reusable-detect-changes.yml

  build-services:
    needs: detect-changes
    if: needs.detect-changes.outputs.matrix != '[]'
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    uses: ./.github/workflows/reusable-service-build.yml
    with:
      service: ${{ matrix.service }}
      goal: "clean verify -Dmaven.test.skip=true"
      active-profile: test
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  build-webapp:
    needs: detect-changes
    if: needs.detect-changes.outputs.webapp_changed == 'true'
    uses: ./.github/workflows/reusable-webapp-build.yml